# Generated by Django 6.0.5 on 2026-06-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_description_publisher_country_member_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelTable(
            name='member',
            table='members',
        ),
    ]
