# Generated by Django 4.2.30 on 2026-07-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_book_num_reviews_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member'},
        ),
    ]
